// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdtCbiWLTXipzQAbDLaoFTC-GkIJ-E0U8',
    appId: '1:560691209470:web:d06f5e4d5e5fd2f16931af',
    messagingSenderId: '560691209470',
    projectId: 'flutter-note-774df',
    authDomain: 'flutter-note-774df.firebaseapp.com',
    storageBucket: 'flutter-note-774df.firebasestorage.app',
    measurementId: 'G-BWL4BVF5PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Rqj8VfbsRCJgsLpt29n6VlhusRKyCsw',
    appId: '1:560691209470:android:ff51bde99712145f6931af',
    messagingSenderId: '560691209470',
    projectId: 'flutter-note-774df',
    storageBucket: 'flutter-note-774df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdPa9r7fhn78ej9OvhjNOt518sS75ucOk',
    appId: '1:560691209470:ios:6c8115defc312a476931af',
    messagingSenderId: '560691209470',
    projectId: 'flutter-note-774df',
    storageBucket: 'flutter-note-774df.firebasestorage.app',
    iosBundleId: 'com.example.flutterNote',
  );
}
